---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  ansible_verbose: true
  # ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
  # require_chef_omnibus: false
  require_ansible_omnibus: true
  require_chef_omnibus: false
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: centos-8
  - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
  - name: default-osquery-syslog
    run_list:
    attributes:
    includes:
      - ubuntu-20.04
      - ubuntu-18.04
      - centos-8
  - name: default-osquery-syslog-fs
    run_list:
    attributes:
    includes:
      - ubuntu-20.04
      - ubuntu-18.04
      - centos-8
  - name: default-profiling
    run_list:
    attributes:
    includes:
      - ubuntu-18.04
  - name: default-fimfiles
    run_list:
    attributes:
    includes:
      - centos-8
      - ubuntu-20.04
      - ubuntu-18.04
  - name: default-auditd
    run_list:
    attributes:
    includes:
      - ubuntu-20.04
  - name: default-fleetmanager
    run_list:
    attributes:
    includes:
      - ubuntu-20.04
