---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: check-case-conflict
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        # exclude: .*/tests/.*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-I, .codespellignore, --exclude-file, templates/osquery.sh.j2]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.2.0
    hooks:
      - id: j2lint
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.8.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
