---
# https://help.ubuntu.com/lts/serverguide/apparmor.html.en

- name: Ensure apparmor packages are present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - apparmor
    - apparmor-utils
    - apparmor-profiles
  register: pkg_result
  until: pkg_result is success

# FIXME! idempotence issue?
- name: Ensure apparmor profile is set
  ansible.builtin.template:
    src: apparmor-usr.bin.osqueryd.j2
    dest: /etc/apparmor.d/opt.osquery.bin.osqueryd
    mode: '0644'
    owner: root
    group: root
    backup: "{{ osquery_backup | default(false) }}"
  notify:
    - Reload osqueryd apparmor profile

- name: Runbindable
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 24
  block:
    - name: Check if /etc/apparmor.d/abstractions/passt exists
      ansible.builtin.stat:
        path: /etc/apparmor.d/abstractions/passt
      register: f_passt
    # https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6063132.html
    # https://gitlab.com/apparmor/apparmor/-/merge_requests/1236
    - name: Workaround apparmor runbindable
      ansible.builtin.replace:
        path: /etc/apparmor.d/abstractions/passt
        regexp: '^  mount options=\(rw, runbindable\) \/,'
        replace: '  mount options=(rw, runbindable) -> /,'
        mode: '0644'
        backup: "{{ osquery_backup | default(false) }}"
      notify:
        - Reload osqueryd apparmor profile
      when:
        - f_passt.stat.exists

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Apply apparmor profile for osquery
  ansible.builtin.command: aa-complain /opt/osquery/bin/osqueryd
  # command: aa-enforce /opt/osquery/bin/osqueryd
  register: aa_status
  changed_when: False
  failed_when: |
    aa_status.rc != 0 and
    "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?" not in aa_status.stderr
  # required on Debian
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Refine policy with `aa-logprof -f /var/log/syslog`
