---
# tasks file for osquery (CentOS specific)

- name: Install osquery repository key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ _osquery_repositorykey }}"
  register: pkg_result
  until: pkg_result is success

- name: Install osquery repository
  ansible.builtin.get_url:
    url: "{{ _osquery_repository }}"
    dest: "/etc/yum.repos.d/{{ _osquery_repository | basename }}"
    mode: '0644'
    backup: "{{ osquery_backup | default(false) }}"

- name: Import selinux
  ansible.builtin.import_tasks: selinux.yml
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker" or
           ansible_virtualization_type == "containerd" or
           ansible_virtualization_type == "container"
          )
        )
