---

- import_tasks: kolide-enroll.yml
  when: kolide_local_enroll

- name: check if osquery is present
  ansible.builtin.stat: path=/etc/osquery
  register: has_osquery
- name: Osquery present
  block:
    - name: ensure directories exist
      ansible.builtin.file:
        dest: "{{ item.d }}"
        state: directory
        mode: "{{ item.m }}"
      with_items:
        - { d: '/var/log/osquery', m: '0755' }
    - name: push extra osquery packs file
      ansible.builtin.template:
        src: "{{ item }}.conf.j2"
        dest: "/opt/osquery/share/osquery/packs/{{ item | basename }}.conf"
        mode: '0644'
        backup: "{{ osquery_backup | default(false) }}"
      with_items: "{{ osquery_upload_packs }}"
      notify:
        - restart osquery
        - restart osquery - docker
    - name: Debug | osquery_packs
      ansible.builtin.debug: var=osquery_packs

    - import_tasks: yara.yml
      when: osquery_yara

    - name: configure osquery
      ansible.builtin.template:
        src: "{{ osquery_template }}"
        dest: /etc/osquery/osquery.conf
        mode: '0644'
        backup: "{{ osquery_backup | default(false) }}"
        validate: 'echo .quit | osqueryi --config_path %s --config_check --verbose'
        # validate: 'egrep -v '^\s*//' %s | tee /tmp/a | python -mjson.tool'
      notify:
        - restart osquery
        - restart osquery - docker
    - name: "ensure osquery var dir exists"
      ansible.builtin.file:
        state: "directory"
        path: "/var/osquery"
        mode: '0755'
    - name: "express the osquery secret to disk"
      ansible.builtin.lineinfile:
        path: "/etc/osquery/osquery_enroll_secret"
        line: "{{ osquery_enroll_secret }}"
        state: present
        owner: "root"
        group: "root"
        mode: "0600"
        create: true
      when:
        - osquery_enroll_secret is defined
      notify:
        - restart osquery
        - restart osquery - docker
    - name: configure osquery flags
      ansible.builtin.template:
        src: "osquery.flags.j2"
        dest: /etc/osquery/osquery.flags
        mode: '0644'
        backup: "{{ osquery_backup | default(false) }}"
      notify:
        - restart osquery
        - restart osquery - docker
    - name: re-validate whole osquery config
      ansible.builtin.shell: 'echo .quit | osqueryi --config_path /etc/osquery/osquery.conf --config_check --verbose'
      changed_when: false
      register: confcheck
      failed_when: "'error' in confcheck.stdout or 'fail' in confcheck.stdout"
    - name: Logrotate
      block:
        - name: ensure logrotate package is present
          ansible.builtin.package:
            name: logrotate
            state: present
          register: pkg_result
          until: pkg_result is success
        - name: add logrotate configuration for osquery log
          ansible.builtin.template:
            src: logrotate-osquery.j2
            dest: /etc/logrotate.d/osquery
            mode: '0644'
            backup: "{{ osquery_backup | default(false) }}"
            validate: 'logrotate -dv %s'
      when: osquery_logrotate|bool
    - name: ensure service is enabled and started
      ansible.builtin.service: name=osqueryd state=started enabled=yes
      when: >
        not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
    - name: Set fact for monit
      ansible.builtin.set_fact:
        monit_osqueryd: true
  when: has_osquery.stat.exists

- name: FIM
  block:
    - name: Debug | ansible_virtualization_type
      ansible.builtin.debug: var=ansible_virtualization_type verbosity=1
    - name: review inotify sysctl settings for osquery
      ansible.posix.sysctl:
        name: "{{ item.n }}"
        value: "{{ item.v }}"
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: "{{ item.f | default(omit) }}"
      with_items:
        - { n: 'fs.inotify.max_user_watches', v: '524288' }
        - { n: 'fs.inotify.max_user_instances', v: '1048576', f: '/etc/sysctl.d/10-lxd-inotify.conf' }
        - { n: 'fs.inotify.max_queued_events', v: '32768' }
  when: >
    osquery_fim and
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or
           ansible_virtualization_type == "containerd" or
           ansible_virtualization_type == "lxc" or
           ansible_virtualization_type == "VirtualPC")
        )

## ensure no auditd at the same time
## https://osquery.readthedocs.io/en/stable/deployment/process-auditing/
- name: process auditing
  block:
    - name: ensure auditd service is disabled and masked
      ansible.builtin.service: name=auditd masked=yes
      when: >
        not (ansible_virtualization_type is defined and (
          ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd"
          )
        )
    - name: ensure auditd is present
      ansible.builtin.package:
        name: "{{ _osquery_auditd_pkg }}"
        state: present
      register: pkg_result
      until: pkg_result is success
  when: osquery_process_auditing|bool

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: get rsyslog version
  ansible.builtin.set_fact:
    rsyslog_v: "{{ ansible_facts.packages['rsyslog'][0]['version'] }}"

- name: Debug | rsyslog version
  ansible.builtin.debug: var=rsyslog_v verbosity=1

# https://osquery.readthedocs.io/en/stable/deployment/syslog/
- name: rsyslog
  block:
    - name: setup rsyslog pipe for osquery communication
      ansible.builtin.template:
        src: osquery-rsyslog.conf.j2
        dest: /etc/rsyslog.d/90-osquery.conf
        mode: '0644'
        backup: "{{ osquery_backup | default(false) }}"
      notify:
        - restart rsyslog
        - restart rsyslog - docker
  when: osquery_rsyslog|bool

- import_tasks: syslog-target.yml
  when: osquery_syslog_target is defined and osquery_syslog_target

- import_tasks: selinux-end.yml
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker" or
          ansible_virtualization_type == "containerd"
          )
        ) and
    ansible_os_family == "RedHat"

- import_tasks: reporting.yml
  when: osquery_reporting
