---
# tasks file for osquery (Debian, Ubuntu specific)

- name: Set fact for arch x86_64
  ansible.builtin.set_fact:
    osquery_deb_arch: amd64
  when: ansible_facts['architecture'] == 'x86_64'
- name: Set fact for arch aarch64
  ansible.builtin.set_fact:
    osquery_deb_arch: arm64
  when: ansible_facts['architecture'] == 'aarch64'

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure dependencies are present
  ansible.builtin.package:
    name:
      - dirmngr
      - apt-transport-https
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Configure osquery APT repository
  become: yes
  ansible.builtin.deb822_repository:
    name: osquery
    types: deb
    uris: "{{ _osquery_repository_uris }}"
    suites: '{{ ansible_facts.distribution_release }}'
    components: main
    architectures: deb
    signed_by: https://pkg.osquery.io/deb/pubkey.gpg
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success
  notify:
    - Refresh apt cache

- name: Import apparmor
  ansible.builtin.import_tasks: apparmor.yml
  when:
    - not is_container|bool
    - ansible_facts['virtualization_type'] != "lxc"
    - osquery_apparmor_enable | bool
