---

# tasks file for osquery (Debian, Ubuntu specific)

- name: Ensure dirmngr is present for apt-key
  ansible.builtin.package:
    name: dirmngr
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Setup osquery APT key
  become: yes
  ansible.builtin.apt_key:
    data: "{{ lookup('file', 'pgp-0x1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B.asc') }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Ensure apt-transport-https is installed
  become: yes
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Configure osquery APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ _osquery_repository }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Import apparmor
  ansible.builtin.import_tasks: apparmor.yml
  when:
    - not is_container|bool
