---

# tasks file for osquery (Debian, Ubuntu specific)

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure dependencies are present
  ansible.builtin.package:
    name:
      - dirmngr
      - apt-transport-https
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Setup osquery APT key
  become: yes
  ansible.builtin.apt_key:
    data: "{{ lookup('file', 'pgp-0x1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B.asc') }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Configure osquery APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ _osquery_repository }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success
  notify:
    - Refresh apt cache

- name: Import apparmor
  ansible.builtin.import_tasks: apparmor.yml
  when:
    - not is_container|bool
