---

- name: RedHat | Ensure selinux context is correctly set
  command: "/sbin/restorecon -F -R -v {{ item }}"  # noqa 301
  with_items:
    - /usr/bin/osqueryd
    - /usr/lib/systemd/system/osqueryd.service
    - /var/log/osquery
    - /etc/osquery
    - /usr/share/osquery/packs
