---

- name: Check if restorecon marker
  ansible.builtin.stat:
    path: /root/.ansible_osquery_restorecon
  register: marker1

- name: selinux
  block:
    - name: RedHat | Ensure selinux context is correctly set
      ansible.builtin.command: "/sbin/restorecon -F -R -v {{ item }}"  # noqa 301
      with_items:
        - /opt/osquery/bin/osqueryd
        - /usr/lib/systemd/system/osqueryd.service
        - /var/log/osquery
        - /etc/osquery
        - /opt/osquery/share/osquery/packs
    - name: RedHat | Create restorecon marker
      ansible.builtin.file:
        path: /root/.ansible_osquery_restorecon
        mode: '0600'
        state: touch
  when: not marker1.stat.exists
