---

- name: Ensure target syslog dir exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "{{ varlog_mode }}"
    group: "{{ varlog_group }}"
  with_items: "{{ osquery_syslog_dirs }}"

- name: Setup rsyslog to send osquery logs to a specific target
  ansible.builtin.template:
    src: rsyslog-osquery-target.conf.j2
    dest: /etc/rsyslog.d/30-osquery-target.conf
    mode: '0644'
    backup: "{{ osquery_backup | default(false) }}"
    validate: 'rsyslogd -d -N 1 -f %s'
  notify:
    - Restart rsyslog
    - Restart rsyslog - docker
