---
# handlers file for osquery

- name: Reload osqueryd apparmor profile
  ansible.builtin.shell: cat /etc/apparmor.d/usr.bin.osqueryd | sudo apparmor_parser -r
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Restart osquery
  ansible.builtin.shell: "systemctl stop osqueryd; sleep 5; systemctl start osqueryd"  # noqa command-instead-of-module
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Restart osquery - docker
  ansible.builtin.service: name=osqueryd state=restarted sleep=5 use=service
  when: >
    (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
    )

- name: Restart rsyslog
  ansible.builtin.service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Restart rsyslog - docker
  ansible.builtin.service: name=rsyslog state=restarted use=service
  when:
    - (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd"))
    - not (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
