---
# handlers file for osquery

- name: reload osqueryd apparmor profile
  ansible.builtin.shell: cat /etc/apparmor.d/usr.bin.osqueryd | sudo apparmor_parser -r
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart osquery
  ansible.builtin.shell: "systemctl stop osqueryd; sleep 5; systemctl start osqueryd"  # noqa 303
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart osquery - docker
  ansible.builtin.service: name=osqueryd state=restarted sleep=5 use=service
  when: >
    (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
    )

- name: restart rsyslog
  ansible.builtin.service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart rsyslog - docker
  ansible.builtin.service: name=rsyslog state=restarted use=service
  when:
    - (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd"))
    - not (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
