---
# handlers file for osquery

- name: Reload osqueryd apparmor profile
  ansible.builtin.shell: cat /etc/apparmor.d/usr.bin.osqueryd | sudo apparmor_parser -r
  when:
    - not is_container|bool

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container|bool

- name: Restart osquery
  ansible.builtin.shell: "systemctl stop osqueryd; sleep 5; systemctl start osqueryd"  # noqa command-instead-of-module
  when:
    - not is_container|bool

- name: Restart osquery - docker
  ansible.builtin.shell: "pkill osqueryd; sleep 5; /usr/bin/osqueryd --flagfile /etc/osquery/osquery.flags --config_path /etc/osquery/osquery.conf --daemonize"
  when:
    - is_container|bool

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not is_container|bool

- name: Restart rsyslog - docker
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - is_container|bool
    - not (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
