---

- name: Verify
  hosts: molecule
  tasks:
    - name: Ensure /etc/osquery/osquery.conf config file is present
      stat:
        path: /etc/osquery/osquery.conf
      register: cfg
    - name: Validate config present
      assert:
        that: cfg.stat.exists and cfg.stat.size != 0

    - name: Ensure process is running
      command: pgrep -u root osqueryd
      register: ps
      changed_when: false
      ignore_errors: true
    - name: Validate ps output
      assert:
        that: ps.stdout
      failed_when: false

    - name: list /var/log/osquery
      command: ls -lA /var/log/osquery
      changed_when: false

    - name: Fetch content of /var/log/osquery/osqueryd.INFO
      slurp:
        src: /var/log/osquery/osqueryd.INFO
      register: info
    - name: Validate /var/log/osquery/osqueryd.INFO
      assert:
        that: >
          "'Log line format:' in info['content'] | b64decode"

    - name: Check if /var/log/osquery/osqueryd.WARNING exists
      stat:
        path: /var/log/osquery/osqueryd.WARNING
      register: warnfile
    - name: Fetch content of /var/log/osquery/osqueryd.WARNING
      slurp:
        src: /var/log/osquery/osqueryd.WARNING
      register: warn
      when: warnfile.stat.exists
    - name: Validate /var/log/osquery/osqueryd.WARNING
      assert:
        that: >
          "'Log line format:' in warn['content'] | b64decode and
          'kernel: Cannot access /dev/osquery' not in warn['content'] | b64decode"
      when: warnfile.stat.exists
